apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: boriscernak/wac-project
  newName: boriscernak/wac-project # {"$imagepolicy":  "wac-hospital:wac-project:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:wac-project:tag"}

- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
